//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLGO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTXUATKHO
    {
        public string IDPhieuXuat { get; set; }
        public string IDSP { get; set; }
        public int SLXuat { get; set; }
    
        public virtual XUUATKHO XUUATKHO { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
