//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLGO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONDATHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONDATHANG()
        {
            this.CTDONDATHANGs = new HashSet<CTDONDATHANG>();
        }
    
        public string IDDDH { get; set; }
        public string IDKH { get; set; }
        public string IDNV { get; set; }
        public string IDLTT { get; set; }
        public string TinhTrang { get; set; }
        public System.DateTime NgayDatHang { get; set; }
        public System.DateTime NgayGiaoHang { get; set; }
        public string DiaChi { get; set; }
        public string IDTT { get; set; }
        public string TenNguoiDH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDONDATHANG> CTDONDATHANGs { get; set; }
        public virtual LOAITHANHTOAN LOAITHANHTOAN { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG1 { get; set; }
        public virtual TINHTRANG TINHTRANG1 { get; set; }
    }
}
