//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLGO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUOIDUNG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NGUOIDUNG()
        {
            this.DONDATHANGs = new HashSet<DONDATHANG>();
            this.DONDATHANGs1 = new HashSet<DONDATHANG>();
            this.HOADONs = new HashSet<HOADON>();
            this.HOADONs1 = new HashSet<HOADON>();
            this.NHAPKHOes = new HashSet<NHAPKHO>();
            this.XUUATKHOes = new HashSet<XUUATKHO>();
        }
    
        public string IDND { get; set; }
        public string MKDN { get; set; }
        public string TenDN { get; set; }
        public string HoND { get; set; }
        public string TenND { get; set; }
        public string SDTND { get; set; }
        public string EmailND { get; set; }
        public bool GioiTinh { get; set; }
        public int DiemThuong { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string IDLND { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONDATHANG> DONDATHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONDATHANG> DONDATHANGs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs1 { get; set; }
        public virtual LOAINGUOIDUNG LOAINGUOIDUNG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHAPKHO> NHAPKHOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XUUATKHO> XUUATKHOes { get; set; }
    }
}
