//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLGO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XUUATKHO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XUUATKHO()
        {
            this.CTXUATKHOes = new HashSet<CTXUATKHO>();
        }
    
        public string IDPhieuXuat { get; set; }
        public System.DateTime NgayXuatKho { get; set; }
        public string IDND { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTXUATKHO> CTXUATKHOes { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
    }
}
